M48
; DRILL file {KiCad 9.0.7} date 2026-01-19T21:12:16-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-19T21:12:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X79.96Y-74.42
X79.96Y-76.96
X79.96Y-79.5
T2
X81.5Y-61.0
X81.5Y-92.5
X164.2Y-61.0
X164.6Y-92.2
M30
