#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define DISPLAY_MODE_INDIVIDUAL 0x00
#define DISPLAY_MODE_COMBINED   0x01

#define DISPLAY_I2C_ADDRESS 0xb1

// Registers
#define REG_OUT_GAIN 0x00
#define REG_IN_GAIN 0x01
#define REG_FILTER_SELECT 0x02
#define REG_FILTER_FREQ 0x03
#define RESERVED1 0x04
#define REG_SAMPLE_RATE 0x05
#define REG_RESET 0x06
#define REG_FILTER_TYPE 0x07
#define REG_FILTER_COEFF0 0x08
#define REG_FILTER_COEFF1 0x09
#define REG_FILTER_COEFF2 0x0a
#define REG_FILTER_COEFF3 0x0b
#define REG_FILTER_COEFF4 0x0c
#define REG_DISPLAY_MODE 0x0d
#define REG_UI_MODE 0x0e
#define REG_FILTER_Q 0x0f
#define REG_FILTER_GAIN 0x10
#define REG_COMMIT 0xff


#endif // CONSTANTS_H_INCLUDED
